/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.healthcare;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Himangshu
 */
public class EnterRecommendation extends javax.swing.JFrame {

    /**
     * Creates new form EnterRecommendation
     */
    ArrayList<String> mPatientInfo;
    String mPatienUsername;
    public EnterRecommendation(String patientUsername) {
        this.mPatienUsername = patientUsername;
        initLocalData();
        initComponents();
    }

    public EnterRecommendation(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        weightHigh = new javax.swing.JTextField();
        weightLow = new javax.swing.JTextField();
        weightFrequency = new javax.swing.JTextField();
        bpSystolicLow = new javax.swing.JTextField();
        bpSystolicHigh = new javax.swing.JTextField();
        bpDiastolicHigh = new javax.swing.JTextField();
        bpDiastolicLow = new javax.swing.JTextField();
        bpFrequency = new javax.swing.JTextField();
        oxySatFrequency = new javax.swing.JTextField();
        temperatureFrequency = new javax.swing.JTextField();
        temperatureHigh = new javax.swing.JTextField();
        oxySatHigh = new javax.swing.JTextField();
        temperatureLow = new javax.swing.JTextField();
        painLevelFrequency = new javax.swing.JTextField();
        moodFrequency = new javax.swing.JTextField();
        oxySatLow = new javax.swing.JTextField();
        painLevel = new javax.swing.JSpinner();
        mood = new javax.swing.JComboBox<>();
        bpNA = new javax.swing.JCheckBox();
        weightNA = new javax.swing.JCheckBox();
        oxyNA = new javax.swing.JCheckBox();
        painNA = new javax.swing.JCheckBox();
        tempNA = new javax.swing.JCheckBox();
        moodNA = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Enter Recommendations for " + mPatientInfo.get(0));

        submitButton.setText("submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jButton2.setText("close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Weight Low");

        jLabel3.setText("Weight Frequency");

        jLabel4.setText("Weight High");

        jLabel5.setText("BP Systolic High");

        jLabel6.setText("BP Systolic Low");

        jLabel7.setText("Temperature Frequency");

        jLabel8.setText("BP Diastolic Low");

        jLabel9.setText("BP Diastolic High");

        jLabel10.setText("Oxygen Saturation Low");

        jLabel11.setText("BP Frequency");

        jLabel12.setText("Oxygen Saturation High");

        jLabel13.setText("Oxy Sat Frequency");

        jLabel14.setText("Temperature Low");

        jLabel15.setText("Temperature High");

        jLabel16.setText("Mood Frequency");

        jLabel17.setText("Pain Level");

        jLabel18.setText("Pain Frequency");

        jLabel19.setText("Mood");

        weightHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightHighActionPerformed(evt);
            }
        });

        weightLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightLowActionPerformed(evt);
            }
        });

        bpSystolicLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpSystolicLowActionPerformed(evt);
            }
        });

        bpSystolicHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpSystolicHighActionPerformed(evt);
            }
        });

        bpDiastolicHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpDiastolicHighActionPerformed(evt);
            }
        });

        bpDiastolicLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpDiastolicLowActionPerformed(evt);
            }
        });

        bpFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpFrequencyActionPerformed(evt);
            }
        });

        oxySatFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oxySatFrequencyActionPerformed(evt);
            }
        });

        temperatureFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureFrequencyActionPerformed(evt);
            }
        });

        temperatureHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureHighActionPerformed(evt);
            }
        });

        oxySatHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oxySatHighActionPerformed(evt);
            }
        });

        temperatureLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureLowActionPerformed(evt);
            }
        });

        painLevelFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                painLevelFrequencyActionPerformed(evt);
            }
        });

        moodFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodFrequencyActionPerformed(evt);
            }
        });

        oxySatLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oxySatLowActionPerformed(evt);
            }
        });

        painLevel.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        mood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Happy", "Sad", "Neutral" }));

        bpNA.setText("N/A");
        bpNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpNAActionPerformed(evt);
            }
        });

        weightNA.setText("N/A");
        weightNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightNAActionPerformed(evt);
            }
        });

        oxyNA.setText("N/A");
        oxyNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oxyNAActionPerformed(evt);
            }
        });

        painNA.setText("N/A");
        painNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                painNAActionPerformed(evt);
            }
        });

        tempNA.setText("N/A");
        tempNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempNAActionPerformed(evt);
            }
        });

        moodNA.setText("N/A");
        moodNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodNAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(28, 28, 28)
                                                .addComponent(oxySatLow, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(bpDiastolicLow))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel1))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bpSystolicLow)
                                                    .addComponent(weightLow))))
                                        .addGap(63, 63, 63)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel9))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(weightHigh, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                    .addComponent(bpSystolicHigh)
                                                    .addComponent(bpDiastolicHigh)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(temperatureHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(oxySatHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(35, 35, 35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(moodFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(moodNA)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(painLevelFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(painNA)
                                        .addGap(15, 15, 15)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(bpFrequency, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                            .addComponent(weightFrequency, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(bpNA))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(weightNA))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oxySatFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(oxyNA))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(temperatureFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tempNA)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submitButton)
                                .addComponent(painLevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(temperatureLow, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(153, 153, 153)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(weightHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightNA))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(bpSystolicLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpSystolicHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(bpDiastolicHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpDiastolicLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpNA))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(oxySatFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oxySatHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oxySatLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oxyNA))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel7)
                    .addComponent(temperatureFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempNA))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(painLevelFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painNA))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel16)
                    .addComponent(moodFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moodNA))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void weightLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightLowActionPerformed

    private void bpSystolicLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpSystolicLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpSystolicLowActionPerformed

    private void bpSystolicHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpSystolicHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpSystolicHighActionPerformed

    private void bpDiastolicHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpDiastolicHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpDiastolicHighActionPerformed

    private void bpDiastolicLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpDiastolicLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpDiastolicLowActionPerformed

    private void bpFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpFrequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpFrequencyActionPerformed

    private void oxySatFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oxySatFrequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oxySatFrequencyActionPerformed

    private void temperatureFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureFrequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureFrequencyActionPerformed

    private void temperatureHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureHighActionPerformed

    private void oxySatHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oxySatHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oxySatHighActionPerformed

    private void temperatureLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureLowActionPerformed

    private void painLevelFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painLevelFrequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_painLevelFrequencyActionPerformed

    private void moodFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodFrequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moodFrequencyActionPerformed

    private void oxySatLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oxySatLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oxySatLowActionPerformed

    private void weightHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightHighActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Integer localBpSystolicHigh, localBpSystolicLow, localBpDiatolicHigh, localBpDiastolicLow, localBpFreq;
        Float localOxySatLow, localOxySatHigh;
        Integer localOxySatFrequency;
        String localPain, localMood;
        Integer localPainFreq, localMoodFreq;
        Float localTempLow, localTempHigh, localWeightLow, localWeightHigh;
        Integer localTempFreq, localWeightFreq;        
        try{            
            if(!bpNA.isSelected()){
                localBpSystolicLow = Integer.parseInt(bpSystolicLow.getText().trim()); 
                localBpSystolicHigh= Integer.parseInt(bpSystolicHigh.getText().trim());
                localBpDiastolicLow = Integer.parseInt(bpDiastolicLow.getText().trim());
                localBpDiatolicHigh = Integer.parseInt(bpDiastolicHigh.getText().trim()); 
                localBpFreq = Integer.parseInt(bpFrequency.getText().trim());
            } else {
                localBpSystolicLow = 0; 
                localBpSystolicHigh= 0;
                localBpDiastolicLow = 0;
                localBpDiatolicHigh = 0; 
                localBpFreq = 0;
            }
             
            if(!oxyNA.isSelected()){
                localOxySatLow = Float.parseFloat(oxySatLow.getText().trim()); 
                localOxySatHigh = Float.parseFloat(oxySatHigh.getText().trim());
                localOxySatFrequency = Integer.parseInt(oxySatFrequency.getText().trim());
            } else {
                localOxySatLow = 0.0f; 
                localOxySatHigh = 0.0f;
                localOxySatFrequency = 0;
            }      
                            
            if(!painNA.isSelected()){
                localPain = painLevel.getValue().toString().trim(); 
                localPainFreq = Integer.parseInt(painLevelFrequency.getText().trim()); 
            } else {
                localPain = ""; 
                localPainFreq = 0;            
            }                
            
            if(!moodNA.isSelected()){
                localMood = (String)mood.getSelectedItem();
                localMoodFreq = Integer.parseInt(moodFrequency.getText().trim());
            } else {
                localMood = "";
                localMoodFreq = 0;
            }

             
            if(!tempNA.isSelected()){
                localTempLow = Float.parseFloat(temperatureLow.getText().trim()); 
                localTempHigh = Float.parseFloat(temperatureHigh.getText().trim()); 
                localTempFreq = Integer.parseInt(temperatureFrequency.getText().trim());
            } else {
                localTempLow = 0.0f; 
                localTempHigh = 0.0f; 
                localTempFreq = 0;
            }

            if(!weightNA.isSelected()){
                localWeightLow = Float.parseFloat(weightLow.getText().trim());
                localWeightHigh = Float.parseFloat(weightHigh.getText().trim());
                localWeightFreq = Integer.parseInt(weightFrequency.getText().trim());
            } else {
                localWeightLow = 0.0f;
                localWeightHigh = 0.0f;
                localWeightFreq = 0;
            }
            
            Database.getInstance().addRecommendation(
                    new Recommendation(localBpSystolicLow,
                localBpSystolicHigh,
                localBpDiastolicLow,
                localBpDiatolicHigh,
                localBpFreq,

                localOxySatLow,
                localOxySatHigh,
                localOxySatFrequency,


                localPain,
                localPainFreq,

                localMood,
                localMoodFreq,

                localTempLow,
                localTempHigh,
                localTempFreq,

                localWeightLow,
                localWeightHigh,
                localWeightFreq), mPatienUsername);
            JOptionPane.showMessageDialog(null, "Recommendation Entered Sucessfully!");
            this.dispose();
        } catch(Exception e){
            System.out.println("The Error in entering reco = " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error in entry ! Please check. Error = " + e.getMessage());
            cleanTextFields();
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void bpNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpNAActionPerformed

    private void weightNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightNAActionPerformed

    private void oxyNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oxyNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oxyNAActionPerformed

    private void painNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_painNAActionPerformed

    private void tempNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempNAActionPerformed

    private void moodNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moodNAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterRecommendation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterRecommendation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterRecommendation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterRecommendation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterRecommendation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bpDiastolicHigh;
    private javax.swing.JTextField bpDiastolicLow;
    private javax.swing.JTextField bpFrequency;
    private javax.swing.JCheckBox bpNA;
    private javax.swing.JTextField bpSystolicHigh;
    private javax.swing.JTextField bpSystolicLow;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> mood;
    private javax.swing.JTextField moodFrequency;
    private javax.swing.JCheckBox moodNA;
    private javax.swing.JCheckBox oxyNA;
    private javax.swing.JTextField oxySatFrequency;
    private javax.swing.JTextField oxySatHigh;
    private javax.swing.JTextField oxySatLow;
    private javax.swing.JSpinner painLevel;
    private javax.swing.JTextField painLevelFrequency;
    private javax.swing.JCheckBox painNA;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox tempNA;
    private javax.swing.JTextField temperatureFrequency;
    private javax.swing.JTextField temperatureHigh;
    private javax.swing.JTextField temperatureLow;
    private javax.swing.JTextField weightFrequency;
    private javax.swing.JTextField weightHigh;
    private javax.swing.JTextField weightLow;
    private javax.swing.JCheckBox weightNA;
    // End of variables declaration//GEN-END:variables

    private void initLocalData() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        try{
            mPatientInfo = Database.getInstance().getNameAndIdForUsername(mPatienUsername);
        } catch(Exception e){
            System.out.println("Error is = " + e.getMessage());
            e.printStackTrace();
        }
                
    }

    private void cleanTextFields() {
        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JTextField || component instanceof JTextArea) {
                JTextComponent specificObject = (JTextComponent) component;
                specificObject.setText("");
            }
        }
    }
}
