package com.healthcare;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rahul
 */
public class HealthSupporter extends javax.swing.JFrame {

    /**
     * Creates new form HealthSupporter
     */
    HsInfo supp1, supp2;
    Database db;
    String username;
    public HealthSupporter(String username) {
        this.username = username;
        db = Database.getInstance();
        try
        {
            ArrayList<String> data = db.getNameAndIdForUsername(username);            
            String name = data.get(0);
            int person_id = Integer.parseInt(data.get(1));            
            ArrayList<HsInfo> arr = db.getHsInfo(person_id);
            supp1 = null;
            supp2 = null;
            if(arr.size() >= 1)
            {
                supp1 = arr.get(0);
                
            }
            if(arr.size() >= 2)
            {
                supp2 = arr.get(1);
            }
        }
        catch(Exception e)
        {
        }
        
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        auth_date1 = new javax.swing.JComboBox<>();
        auth_month1 = new javax.swing.JComboBox<>();
        auth_year1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        addPrimary = new javax.swing.JButton();
        editPrimary = new javax.swing.JButton();
        addSecondary = new javax.swing.JButton();
        editSecondary = new javax.swing.JButton();
        primaryUsername = new javax.swing.JComboBox<>();
        changePrimary = new javax.swing.JButton();
        changeSecondary = new javax.swing.JButton();
        primaryLbl = new javax.swing.JLabel();
        primary_auth = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        auth_date2 = new javax.swing.JComboBox<>();
        auth_month2 = new javax.swing.JComboBox<>();
        auth_year2 = new javax.swing.JComboBox<>();
        secondaryUsername = new javax.swing.JComboBox<>();
        secondaryLbl = new javax.swing.JLabel();
        secondary_auth = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Primary Health Supporter:");

        jLabel3.setText("Your secondary health supporter");

        jLabel6.setText("Username");

        jLabel7.setText("Authorization Date:");

        auth_date1.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getDays()));

        auth_month1.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getMonths()));

        auth_year1.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getYears()));

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });



        addPrimary.setText("Add");
        addPrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPrimaryActionPerformed(evt);
            }
        });
        if(supp1 != null)
        {
            addPrimary.setEnabled(false);
        }
        else
        {
            addPrimary.setEnabled(true);
        }

        editPrimary.setText("Edit Supporter's Profile");
        if(supp1 != null)
        {
            editPrimary.setEnabled(true);
        }
        else
        {
            editPrimary.setEnabled(false);
        }
        editPrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPrimaryActionPerformed(evt);
            }
        });

        addSecondary.setText("Add");
        addSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSecondaryActionPerformed(evt);
            }
        });

        editSecondary.setText("Edit Supporter's Profile");
        if(supp2 != null)
        {
            editSecondary.setEnabled(true);
        }
        else
        {
            editSecondary.setEnabled(false);
        }
        editSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSecondaryActionPerformed(evt);
            }
        });

        primaryUsername.setModel(new javax.swing.DefaultComboBoxModel<>(db.getSupporters()));
        if(supp1 == null)
        {
            primaryUsername.setVisible(true);
            auth_date1.setVisible(true);
            auth_month1.setVisible(true);
            auth_year1.setVisible(true);
        }
        else
        {
            primaryUsername.setVisible(false);
            auth_date1.setVisible(false);
            auth_month1.setVisible(false);
            auth_year1.setVisible(false);
        }

        changePrimary.setText("Change Supporter");
        changePrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePrimaryActionPerformed(evt);
            }
        });

        changeSecondary.setText("Change Supporter");
        changeSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSecondaryActionPerformed(evt);
            }
        });

        if(supp1 != null)
        {
            primaryLbl.setText(supp1.username);
        }

        if(supp1 != null)
        {

            String[] date = DateFormatManager.getYearMonthDayFromDate(supp1.auth_date);
            primary_auth.setText(date[2] + "/" + date[1] + "/" + date[0]);
        }

        jLabel8.setText("Authorization Date:");

        auth_date2.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getDays()));

        auth_month2.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getMonths()));

        auth_year2.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getYears()));

        secondaryUsername.setModel(new javax.swing.DefaultComboBoxModel<>(db.getSupporters()));
        if(supp2 == null)
        {
            secondaryUsername.setVisible(true);
            auth_date2.setVisible(true);
            auth_month2.setVisible(true);
            auth_year2.setVisible(true);
        }
        else
        {
            secondaryUsername.setVisible(false);
            auth_date2.setVisible(false);
            auth_month2.setVisible(false);
            auth_year2.setVisible(false);
        }

        if(supp2 != null)
        {
            secondaryLbl.setText(supp2.username);
        }

        if(supp2 != null)
        {
            String[] date = DateFormatManager.getYearMonthDayFromDate(supp2.auth_date);
            secondary_auth.setText(date[2] + "/" + date[1] + "/" + date[0]);
        }

        jLabel11.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(60, 60, 60)
                                .addComponent(addPrimary))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(80, 80, 80)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primaryLbl)
                                    .addComponent(primary_auth))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(primaryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(auth_date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addComponent(auth_month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(auth_year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(79, 79, 79)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondaryLbl)
                            .addComponent(secondary_auth))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secondaryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(auth_date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(auth_month2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(auth_year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changePrimary)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(addSecondary)
                                .addGap(20, 20, 20)
                                .addComponent(changeSecondary)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editSecondary)
                            .addComponent(editPrimary))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addPrimary)
                    .addComponent(editPrimary)
                    .addComponent(changePrimary))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(primaryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primaryLbl))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(auth_date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primary_auth))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSecondary)
                    .addComponent(editSecondary)
                    .addComponent(changeSecondary))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(secondaryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondaryLbl))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(auth_date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_month2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondary_auth))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(10, 10, 10))
        );

        if(supp2 != null)
        {
            addSecondary.setEnabled(false);
        }
        else
        {
            addSecondary.setEnabled(true);
        }
        if(supp1 != null)
        {
            changePrimary.setEnabled(true);
        }
        else
        {
            changePrimary.setEnabled(false);
        }
        if(supp2 != null)
        {
            changeSecondary.setEnabled(true);
        }
        else
        {
            changeSecondary.setEnabled(false);
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editPrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPrimaryActionPerformed
        // TODO add your handling code here:
        
        new Profile(supp1.username).setVisible(true);
        
    }//GEN-LAST:event_editPrimaryActionPerformed

    private void editSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSecondaryActionPerformed
        // TODO add your handling code here:
        
        new Profile(supp2.username).setVisible(true);
        
        
    }//GEN-LAST:event_editSecondaryActionPerformed

    private void changePrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePrimaryActionPerformed
        // TODO add your handling code here:
        new ChangeSupporter(this.username, this.supp1.username).setVisible(true);
    }//GEN-LAST:event_changePrimaryActionPerformed

    private void changeSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSecondaryActionPerformed
        // TODO add your handling code here:
        new ChangeSupporter(this.username, this.supp2.username).setVisible(true);
    }//GEN-LAST:event_changeSecondaryActionPerformed


    

    private void addPrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPrimaryActionPerformed
        // TODO add your handling code here:
        Date auth_date = DateFormatManager.getDate((String)auth_date1.getSelectedItem(), (String)auth_month1.getSelectedItem(), (String)auth_year1.getSelectedItem());
        try{
            
            ArrayList<String> out = db.addHealthSupporter(username, (String)(primaryUsername.getSelectedItem()), auth_date);
            JOptionPane.showMessageDialog(null, out.get(1));
        }
        catch(SQLException sql)
        {
            
        }
        
        
    }//GEN-LAST:event_addPrimaryActionPerformed

    private void addSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSecondaryActionPerformed
        // TODO add your handling code here:
        Date auth_date = DateFormatManager.getDate((String)auth_date2.getSelectedItem(), (String)auth_month2.getSelectedItem(), (String)auth_year2.getSelectedItem());
        
        
        try{
            String selected = (String)(secondaryUsername.getSelectedItem());
            if(!selected.equals(""))
            {
                ArrayList<String> out = db.addHealthSupporter(username, selected , auth_date);
                JOptionPane.showMessageDialog(null, out.get(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "please select a username");
            }
                   
            
        }
        catch(SQLException sql)
        {
            
        }
    }//GEN-LAST:event_addSecondaryActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthSupporter("").setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPrimary;
    private javax.swing.JButton addSecondary;
    private javax.swing.JComboBox<String> auth_date1;
    private javax.swing.JComboBox<String> auth_date2;
    private javax.swing.JComboBox<String> auth_month1;
    private javax.swing.JComboBox<String> auth_month2;
    private javax.swing.JComboBox<String> auth_year1;
    private javax.swing.JComboBox<String> auth_year2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton changePrimary;
    private javax.swing.JButton changeSecondary;
    private javax.swing.JButton editPrimary;
    private javax.swing.JButton editSecondary;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel primaryLbl;
    private javax.swing.JComboBox<String> primaryUsername;
    private javax.swing.JLabel primary_auth;
    private javax.swing.JLabel secondaryLbl;
    private javax.swing.JComboBox<String> secondaryUsername;
    private javax.swing.JLabel secondary_auth;
    // End of variables declaration//GEN-END:variables
}
