package com.healthcare;

import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rahul
 */
public class HealthSupporter extends javax.swing.JFrame {

    /**
     * Creates new form HealthSupporter
     */
    String supp1_username = "", supp1_name = "";
    String supp2_username = "", supp2_name = "";
    Database db;
    String username;
    public HealthSupporter(String username) {
        this.username = username;
        db = Database.getInstance();
        try
        {
            ArrayList<String> data = db.getNameAndIdForUsername(username);            
            String name = data.get(0);
            int person_id = Integer.parseInt(data.get(1));            
            ArrayList<HsInfo> arr = db.getHsInfo(person_id);
            if(arr.size() >= 1)
            {
                supp1_username = arr.get(0).username;
                supp1_name = arr.get(0).name;
            }
            if(arr.size() >= 2)
            {
                supp2_username = arr.get(1).username;
                supp2_name = arr.get(1).name;
            }
                
        }
        catch(Exception e)
        {
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        auth_date1 = new javax.swing.JComboBox<>();
        auth_month1 = new javax.swing.JComboBox<>();
        auth_year1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        auth_date2 = new javax.swing.JComboBox<>();
        auth_month2 = new javax.swing.JComboBox<>();
        auth_year2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addPrimary = new javax.swing.JButton();
        editPrimary = new javax.swing.JButton();
        addSecondary = new javax.swing.JButton();
        editSecondary = new javax.swing.JButton();
        primaryUsername = new javax.swing.JComboBox<>();
        secondaryUsername = new javax.swing.JComboBox<>();
        changePrimary = new javax.swing.JButton();
        changeSecondary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Primary Health Supporter:");

        jLabel3.setText("Your secondary health supporter");

        jLabel6.setText("Username");

        jLabel7.setText("Authorization Date:");

        auth_date1.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getDays()));

        auth_month1.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getMonths()));

        auth_year1.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getYears()));

        jLabel9.setText("Username");

        jLabel10.setText("Authorization Date:");

        auth_date2.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getDays()));

        auth_month2.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getMonths()));

        auth_year2.setModel(new javax.swing.DefaultComboBoxModel<>(DateFormatManager.getYears()));

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");

        addPrimary.setText("Add");

        editPrimary.setText("Edit Supporter's Profile");
        if(supp1_username.equals(""))
        {
            editPrimary.setEnabled(false);
            changePrimary.setEnabled(false);
        }
        else
        {
            addPrimary.setEnabled(false);
            changePrimary.setEnabled(true);
        }
        editPrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPrimaryActionPerformed(evt);
            }
        });

        addSecondary.setText("Add");

        editSecondary.setText("Edit Supporter's Profile");
        if(supp2_username.equals(""))
        {
            editSecondary.setEnabled(false);
            changeSecondary.setEnabled(false);
        }
        else
        {
            addSecondary.setEnabled(false);
            changeSecondary.setEnabled(true);
        }
        editSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSecondaryActionPerformed(evt);
            }
        });

        primaryUsername.setModel(new javax.swing.DefaultComboBoxModel<>(db.getSupporters()));
        primaryUsername.setSelectedItem(supp1_username);

        secondaryUsername.setModel(new javax.swing.DefaultComboBoxModel<>(db.getSupporters()));
        secondaryUsername.setSelectedItem(supp2_username);

        changePrimary.setText("Change Supporter");
        changePrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePrimaryActionPerformed(evt);
            }
        });

        changeSecondary.setText("Change Supporter");
        changeSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSecondaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(26, 26, 26)
                            .addComponent(addSecondary)
                            .addGap(18, 18, 18)
                            .addComponent(changeSecondary)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editSecondary))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addComponent(addPrimary))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(79, 79, 79)
                                            .addComponent(primaryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(auth_date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(12, 12, 12)
                                    .addComponent(auth_month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(auth_year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(changePrimary)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editPrimary)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondaryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(auth_date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(auth_month2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(auth_year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addPrimary)
                    .addComponent(editPrimary)
                    .addComponent(changePrimary))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(primaryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(auth_date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSecondary)
                    .addComponent(editSecondary)
                    .addComponent(changeSecondary))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(secondaryUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(auth_date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_month2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editPrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPrimaryActionPerformed
        // TODO add your handling code here:
        new Profile(this.supp1_username).setVisible(true);
    }//GEN-LAST:event_editPrimaryActionPerformed

    private void editSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSecondaryActionPerformed
        // TODO add your handling code here:
        new Profile(this.supp2_username).setVisible(true);
    }//GEN-LAST:event_editSecondaryActionPerformed

    private void changePrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePrimaryActionPerformed
        // TODO add your handling code here:
        new ChangeSupporter(this.username, this.supp1_username).setVisible(true);
    }//GEN-LAST:event_changePrimaryActionPerformed

    private void changeSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSecondaryActionPerformed
        // TODO add your handling code here:
        new ChangeSupporter(this.username, this.supp2_username).setVisible(true);
    }//GEN-LAST:event_changeSecondaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthSupporter("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPrimary;
    private javax.swing.JButton addSecondary;
    private javax.swing.JComboBox<String> auth_date1;
    private javax.swing.JComboBox<String> auth_date2;
    private javax.swing.JComboBox<String> auth_month1;
    private javax.swing.JComboBox<String> auth_month2;
    private javax.swing.JComboBox<String> auth_year1;
    private javax.swing.JComboBox<String> auth_year2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton changePrimary;
    private javax.swing.JButton changeSecondary;
    private javax.swing.JButton editPrimary;
    private javax.swing.JButton editSecondary;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> primaryUsername;
    private javax.swing.JComboBox<String> secondaryUsername;
    // End of variables declaration//GEN-END:variables
}
